### PR TITLE
feat(keyboard checkbox): Make checkboxes functionality also work when used with keyboard (space or enter)

### PR DESCRIPTION
**Pull request by Cyclodex**
Finding and implementing a workaround for the clipboard feature so it also works nicely with the keyboard.

### CODE REVIEW

**Comment by davidsandoz** [comment]
Awesome! Thanks Fäbu 👍

**Comment by Cyclodex** [comment]
I will deploy the new version on the weekend, then you can test and verify :)

**Comment by Cyclodex** [comment]
Done - please review, I hope the release is working fine!

**Comment by davidsandoz** [comment]
Seems to be working, thanks again! 🤘

**Comment by Cyclodex** [comment]
Phew, nice! :D Welcome! Thanks for the request.
Nice to see that you still use it!
Just sync if there are some changes you need to discuss at some point.

**Pull request merged**
