### PR TITLE
Using the GPLv3

### PR DESCRIPTION
**Pull request by Cyclodex**
Adding the GNU General Public License v3.0

### CODE REVIEW

**Comment by Cyclodex** [comment]
Got request in #75 to add a license.

I think I will go with the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/).
This because I want that changes to it have to be contributed/shared and stay available to all people.

https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

What do you think @pfiaux ?

**Comment by pfiaux** [comment]
I think that's fine, you're using angular which is MIT, and anyways it's not bundled with it you have to install it so it's not distributed with cyclone. Same for the other dependencies they're not really bundled with it.

You probably also want to change the package.json file, remove private: true and change license to `GPL-3.0` or `GPL-3.0+` even if you're not publishing it on npm.

**Review by pfiaux — APPROVED** [review]
As I mentioned update package.json to match license:

* remove private: true 
* change license to GPL-3.0 or GPL-3.0+ e

**Comment by Cyclodex** [comment]
Thanks @pfiaux , its done and merged.

**Pull request merged**
